export const pathAddress =
  "https://thaiaddressapi-thaikub.herokuapp.com/v1/thailand/provinces";

export const GET_DASHBOARD_REQUEST = "GET_DASHBOARD_REQUEST";
export const GET_DASHBOARD_SUCCESS = "GET_DASHBOARD_SUCCESS";
export const GET_DASHBOARD_ERROR = "GET_DASHBOARD_ERROR";
export const GET_ADDRESS_REQUEST = "GET_ADDRESS_REQUEST";
export const GET_ADDRESS_SUCCESS = "GET_ADDRESS_SUCCESS";
export const GET_ADDRESS_ERROR = "GET_ADDRESS_ERROR";
export const GET_ADDRESS_DISTRICT_REQUEST = "GET_ADDRESS_DISTRICT_REQUEST";
export const GET_ADDRESS_DISTRICT_SUCCESS = "GET_ADDRESS_DISTRICT_SUCCESS";
export const GET_ADDRESS_DISTRICT_ERROR = "GET_ADDRESS_DISTRICT_ERROR";
export const GET_ADDRESS_SUBDISTRICT_REQUEST =
  "GET_ADDRESS_SUBDISTRICT_REQUEST";
export const GET_ADDRESS_SUBDISTRICT_SUCCESS =
  "GET_ADDRESS_SUBDISTRICT_SUCCESS";
export const GET_ADDRESS_SUBDISTRICT_ERROR = "GET_ADDRESS_SUBDISTRICT_ERROR";
export const CREATE_PROFILE_REQUEST = "CREATE_PROFILE_REQUEST";
export const CREATE_PROFILE_SUCCESS = "CREATE_PROFILE_SUCCESS";
export const CREATE_PROFILE_ERROR = "CREATE_PROFILE_ERROR";
export const SHOW_DATA = "SHOW_DATA";
export const SET_CURRENT_STEP = "SET_CURRENT_STEP";
